import fs from 'fs';
import path from 'path';
import type { AnalysisResult, Framework, FileChange } from '../types.js';

export async function generatePluginCode(
  rootDir: string,
  analysis: AnalysisResult,
  framework: Framework
): Promise<FileChange[]> {
  const changes: FileChange[] = [];

  if (framework === 'nextjs' || framework === 'react') {
    // Generate provider wrapper
    const providerChange = generateNovaProvider(rootDir, framework);
    if (providerChange) {
      changes.push(providerChange);
    }

    // Update root layout to include provider
    const layoutChange = await updateRootLayout(rootDir, framework);
    if (layoutChange) {
      changes.push(layoutChange);
    }

    // Generate environment variable example
    changes.push(generateEnvExample(rootDir));
  }

  return changes;
}

function generateNovaProvider(rootDir: string, framework: Framework): FileChange | null {
  const providerPath = 'components/providers/NovaProvider.tsx';
  const fullPath = path.join(rootDir, providerPath);

  // Check if file already exists
  if (fs.existsSync(fullPath)) {
    return null;
  }

  const content = `'use client';

import { NovaProvider as BaseNovaProvider } from '@nova/plugin/react';

interface NovaProviderProps {
  children: React.ReactNode;
}

/**
 * Nova Analytics Provider
 * Generated by nova-agent
 *
 * Wraps your app to enable feature analytics tracking.
 * Make sure to set NEXT_PUBLIC_NOVA_API_KEY in your environment.
 */
export function NovaProvider({ children }: NovaProviderProps) {
  const apiKey = process.env.NEXT_PUBLIC_NOVA_API_KEY;

  if (!apiKey) {
    console.warn('[Nova] NEXT_PUBLIC_NOVA_API_KEY not set - analytics disabled');
    return <>{children}</>;
  }

  return (
    <BaseNovaProvider
      apiKey={apiKey}
      disabled={process.env.NODE_ENV === 'development'}
    >
      {children}
    </BaseNovaProvider>
  );
}
`;

  return {
    path: providerPath,
    content,
    operation: 'create',
    description: 'Nova analytics provider component',
  };
}

async function updateRootLayout(
  rootDir: string,
  framework: Framework
): Promise<FileChange | null> {
  // Find the root layout file
  const possibleLayouts = [
    'app/layout.tsx',
    'app/layout.jsx',
    'src/app/layout.tsx',
    'src/app/layout.jsx',
    'pages/_app.tsx',
    'pages/_app.jsx',
    'src/pages/_app.tsx',
    'src/pages/_app.jsx',
  ];

  let layoutPath: string | null = null;
  for (const layout of possibleLayouts) {
    const fullPath = path.join(rootDir, layout);
    if (fs.existsSync(fullPath)) {
      layoutPath = layout;
      break;
    }
  }

  if (!layoutPath) {
    return null;
  }

  const fullPath = path.join(rootDir, layoutPath);
  const content = fs.readFileSync(fullPath, 'utf-8');

  // Check if NovaProvider is already imported
  if (content.includes('NovaProvider') || content.includes('@nova/plugin')) {
    return null;
  }

  // Determine the import path based on layout location
  const isAppRouter = layoutPath.includes('app/');
  const importPath = layoutPath.startsWith('src/')
    ? '@/components/providers/NovaProvider'
    : '../components/providers/NovaProvider';

  let newContent: string;

  if (isAppRouter) {
    // App Router layout
    newContent = addProviderToAppLayout(content, importPath);
  } else {
    // Pages Router _app
    newContent = addProviderToPagesApp(content, importPath);
  }

  if (newContent === content) {
    return null;
  }

  return {
    path: layoutPath,
    content: newContent,
    operation: 'modify',
    description: 'Add NovaProvider to root layout',
  };
}

function addProviderToAppLayout(content: string, importPath: string): string {
  // Add import at the top
  const importStatement = `import { NovaProvider } from '${importPath}';\n`;

  // Find where to add import (after existing imports)
  const importMatch = content.match(/^(import .+\n)+/m);
  let newContent: string;

  if (importMatch) {
    const insertPos = importMatch.index! + importMatch[0].length;
    newContent = content.slice(0, insertPos) + importStatement + content.slice(insertPos);
  } else {
    newContent = importStatement + content;
  }

  // Wrap children with NovaProvider
  // Look for {children} and wrap it
  newContent = newContent.replace(
    /(\{children\})/g,
    '<NovaProvider>{children}</NovaProvider>'
  );

  return newContent;
}

function addProviderToPagesApp(content: string, importPath: string): string {
  // Add import at the top
  const importStatement = `import { NovaProvider } from '${importPath}';\n`;

  // Find where to add import
  const importMatch = content.match(/^(import .+\n)+/m);
  let newContent: string;

  if (importMatch) {
    const insertPos = importMatch.index! + importMatch[0].length;
    newContent = content.slice(0, insertPos) + importStatement + content.slice(insertPos);
  } else {
    newContent = importStatement + content;
  }

  // Wrap Component with NovaProvider
  newContent = newContent.replace(
    /(<Component\s+{\.\.\.pageProps}\s*\/>)/g,
    '<NovaProvider><Component {...pageProps} /></NovaProvider>'
  );

  return newContent;
}

function generateEnvExample(rootDir: string): FileChange {
  const envExamplePath = '.env.example';
  const fullPath = path.join(rootDir, envExamplePath);

  let content = '';

  // Read existing env.example if it exists
  if (fs.existsSync(fullPath)) {
    content = fs.readFileSync(fullPath, 'utf-8');

    // Check if already has Nova API key
    if (content.includes('NOVA_API_KEY')) {
      return {
        path: envExamplePath,
        content,
        operation: 'modify',
        description: 'Nova API key already in .env.example',
      };
    }

    content += '\n';
  }

  content += `# Nova Analytics
# Get your API key from the Nova admin dashboard
NEXT_PUBLIC_NOVA_API_KEY=nova_your_api_key_here
`;

  return {
    path: envExamplePath,
    content,
    operation: fs.existsSync(fullPath) ? 'modify' : 'create',
    description: 'Add Nova API key to environment example',
  };
}
