import type { SyntheticUser } from '../../_lib/types/synthetic-user';

/**
 * Sample personas for demo purposes
 * These reflect realistic South African demographics with varied professions,
 * income levels, locations (including townships), and lifestyle attributes.
 *
 * Distribution logic applied:
 * - ~33% doctors are smokers (1 of 3)
 * - Income correlates with education
 * - Township residents reflect urban proximity
 * - Tech savviness correlates with age
 */
export const samplePersonas: SyntheticUser[] = [
  // === HEALTHCARE PROFESSIONALS ===
  {
    id: 'persona-001',
    tenantId: 'demo-tenant',
    firstName: 'Thabo',
    lastName: 'Molefe',
    avatarSeed: 'thabo-molefe-001',
    bio: 'General practitioner with 12 years of experience. Passionate about community health and primary care in underserved areas.',
    age: 42,
    ageRange: 'RANGE_35_44',
    gender: 'MALE',
    heightCm: 178,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Johannesburg',
    township: 'Soweto',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'PROFESSIONAL',
    fieldOfStudy: 'Medicine',
    almaMater: 'University of the Witwatersrand',
    graduationYear: 2006,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Doctor',
    jobTitle: 'General Practitioner',
    industry: 'Healthcare',
    company: 'Chris Hani Baragwanath Hospital',
    yearsInRole: 12,
    yearsInIndustry: 16,
    isRemote: false,
    incomeRange: 'RANGE_150K_200K',
    monthlyIncome: 180000,
    currency: 'ZAR',
    maritalStatus: 'MARRIED',
    householdSize: 4,
    numberOfChildren: 2,
    childrenAges: [8, 12],
    housingType: 'OWN_HOUSE',
    hasVehicle: true,
    vehicleCount: 2,
    hasPets: false,
    smokingStatus: 'NEVER', // Doctor who doesn't smoke
    alcoholConsumption: 'SOCIAL',
    exerciseFrequency: 'FEW_TIMES_WEEK',
    dietType: 'OMNIVORE',
    sleepHours: 6,
    stressLevel: 'HIGH',
    techSavviness: 'INTERMEDIATE',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'LinkedIn', 'Facebook'],
    hobbies: ['Golf', 'Reading', 'Gardening'],
    interests: ['Public health', 'Medical technology', 'Education'],
    values: ['Family', 'Community service', 'Excellence'],
    mbtiType: 'ISTJ',
    shoppingPreference: 'MIXED',
    priceConsciousness: 'MODERATE',
    brandLoyalty: 'HIGH',
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.95,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },
  {
    id: 'persona-002',
    tenantId: 'demo-tenant',
    firstName: 'Ayanda',
    lastName: 'Nkosi',
    avatarSeed: 'ayanda-nkosi-002',
    bio: 'Pediatric specialist focused on child development. Advocates for early childhood nutrition programs.',
    age: 38,
    ageRange: 'RANGE_35_44',
    gender: 'FEMALE',
    heightCm: 165,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'KwaZulu-Natal',
    city: 'Durban',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'PROFESSIONAL',
    fieldOfStudy: 'Pediatric Medicine',
    almaMater: 'University of KwaZulu-Natal',
    graduationYear: 2010,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Doctor',
    jobTitle: 'Pediatrician',
    industry: 'Healthcare',
    yearsInRole: 8,
    yearsInIndustry: 12,
    incomeRange: 'RANGE_200K_300K',
    monthlyIncome: 220000,
    currency: 'ZAR',
    maritalStatus: 'MARRIED',
    householdSize: 3,
    numberOfChildren: 1,
    housingType: 'OWN_APARTMENT',
    smokingStatus: 'NEVER', // Doctor who doesn't smoke
    alcoholConsumption: 'RARELY',
    exerciseFrequency: 'ONCE_WEEK',
    techSavviness: 'ADVANCED',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'Instagram', 'LinkedIn'],
    interests: ['Child development', 'Yoga', 'Travel'],
    values: ['Health', 'Family', 'Education'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.92,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },
  {
    id: 'persona-003',
    tenantId: 'demo-tenant',
    firstName: 'Johan',
    lastName: 'van der Berg',
    avatarSeed: 'johan-vdb-003',
    bio: 'Emergency room surgeon with a demanding schedule. Struggles with work-life balance.',
    age: 48,
    ageRange: 'RANGE_45_54',
    gender: 'MALE',
    heightCm: 182,
    eyeColor: 'Blue',
    hairColor: 'Grey',
    ethnicity: 'White',
    country: 'South Africa',
    region: 'Western Cape',
    city: 'Cape Town',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'PROFESSIONAL',
    fieldOfStudy: 'Surgery',
    almaMater: 'University of Cape Town',
    graduationYear: 2000,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Doctor',
    jobTitle: 'Trauma Surgeon',
    industry: 'Healthcare',
    yearsInRole: 15,
    yearsInIndustry: 22,
    incomeRange: 'OVER_300K',
    monthlyIncome: 350000,
    currency: 'ZAR',
    maritalStatus: 'DIVORCED',
    householdSize: 1,
    housingType: 'OWN_APARTMENT',
    smokingStatus: 'OCCASIONAL', // Doctor who occasionally smokes (stress)
    alcoholConsumption: 'MODERATE',
    exerciseFrequency: 'RARELY',
    stressLevel: 'VERY_HIGH',
    techSavviness: 'INTERMEDIATE',
    primaryDevice: 'DESKTOP',
    hobbies: ['Photography', 'Wine tasting'],
    interests: ['Medical research', 'Classical music'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.88,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === ENGINEERS & TECH ===
  {
    id: 'persona-004',
    tenantId: 'demo-tenant',
    firstName: 'Sipho',
    lastName: 'Dlamini',
    avatarSeed: 'sipho-dlamini-004',
    bio: 'Software engineer working on fintech solutions. Grew up in Alexandra and now mentors young developers.',
    age: 29,
    ageRange: 'RANGE_25_34',
    gender: 'MALE',
    heightCm: 175,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Johannesburg',
    township: 'Alexandra',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'BACHELORS',
    fieldOfStudy: 'Computer Science',
    almaMater: 'University of Johannesburg',
    graduationYear: 2018,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Software Engineer',
    jobTitle: 'Senior Developer',
    industry: 'Technology',
    company: 'Standard Bank',
    yearsInRole: 3,
    yearsInIndustry: 6,
    isRemote: true,
    incomeRange: 'RANGE_75K_100K',
    monthlyIncome: 85000,
    currency: 'ZAR',
    maritalStatus: 'SINGLE',
    householdSize: 1,
    housingType: 'RENT_APARTMENT',
    hasVehicle: true,
    vehicleCount: 1,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'SOCIAL',
    exerciseFrequency: 'FEW_TIMES_WEEK',
    techSavviness: 'EXPERT',
    primaryDevice: 'DESKTOP',
    socialPlatforms: ['Twitter', 'LinkedIn', 'GitHub', 'Discord'],
    hobbies: ['Gaming', 'Coding side projects', 'Basketball'],
    interests: ['Cryptocurrency', 'AI/ML', 'Startups'],
    values: ['Innovation', 'Community', 'Education'],
    mbtiType: 'INTP',
    shoppingPreference: 'ONLINE',
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.94,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },
  {
    id: 'persona-005',
    tenantId: 'demo-tenant',
    firstName: 'Priya',
    lastName: 'Naidoo',
    avatarSeed: 'priya-naidoo-005',
    bio: 'Data scientist passionate about using analytics to solve real-world problems. Active in women-in-tech initiatives.',
    age: 32,
    ageRange: 'RANGE_25_34',
    gender: 'FEMALE',
    heightCm: 160,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Indian',
    country: 'South Africa',
    region: 'KwaZulu-Natal',
    city: 'Durban',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'MASTERS',
    fieldOfStudy: 'Data Science',
    almaMater: 'University of Cape Town',
    graduationYear: 2016,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Data Scientist',
    jobTitle: 'Lead Data Scientist',
    industry: 'Technology',
    yearsInRole: 4,
    yearsInIndustry: 8,
    incomeRange: 'RANGE_100K_150K',
    monthlyIncome: 120000,
    currency: 'ZAR',
    maritalStatus: 'MARRIED',
    householdSize: 2,
    housingType: 'OWN_APARTMENT',
    smokingStatus: 'NEVER',
    exerciseFrequency: 'DAILY',
    dietType: 'VEGETARIAN',
    techSavviness: 'EXPERT',
    primaryDevice: 'DESKTOP',
    socialPlatforms: ['LinkedIn', 'Twitter', 'Medium'],
    interests: ['Machine learning', 'Women in STEM', 'Sustainability'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.93,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === TEACHERS & EDUCATORS ===
  {
    id: 'persona-006',
    tenantId: 'demo-tenant',
    firstName: 'Nomsa',
    lastName: 'Mthembu',
    avatarSeed: 'nomsa-mthembu-006',
    bio: 'High school mathematics teacher in a township school. Dedicated to improving educational outcomes despite limited resources.',
    age: 45,
    ageRange: 'RANGE_45_54',
    gender: 'FEMALE',
    heightCm: 162,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Johannesburg',
    township: 'Katlehong',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'BACHELORS',
    fieldOfStudy: 'Education',
    almaMater: 'University of South Africa',
    graduationYear: 2002,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Teacher',
    jobTitle: 'Senior Mathematics Teacher',
    industry: 'Education',
    yearsInRole: 18,
    yearsInIndustry: 22,
    incomeRange: 'RANGE_25K_50K',
    monthlyIncome: 38000,
    currency: 'ZAR',
    maritalStatus: 'WIDOWED',
    householdSize: 3,
    numberOfChildren: 2,
    childrenAges: [19, 22],
    housingType: 'OWN_HOUSE',
    hasVehicle: true,
    vehicleCount: 1,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'RARELY',
    exerciseFrequency: 'RARELY',
    techSavviness: 'BASIC',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'Facebook'],
    hobbies: ['Church activities', 'Gardening', 'Reading'],
    interests: ['Education policy', 'Youth development', 'Community service'],
    values: ['Faith', 'Education', 'Family'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.91,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === RETAIL & SERVICE ===
  {
    id: 'persona-007',
    tenantId: 'demo-tenant',
    firstName: 'Lerato',
    lastName: 'Mokoena',
    avatarSeed: 'lerato-mokoena-007',
    bio: 'Retail store manager working towards starting her own business. Juggles work and studying part-time.',
    age: 28,
    ageRange: 'RANGE_25_34',
    gender: 'FEMALE',
    heightCm: 168,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Pretoria',
    township: 'Mamelodi',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'SOME_COLLEGE',
    fieldOfStudy: 'Business Management',
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Retail Manager',
    jobTitle: 'Store Manager',
    industry: 'Retail',
    company: 'Shoprite',
    yearsInRole: 2,
    yearsInIndustry: 6,
    incomeRange: 'RANGE_25K_50K',
    monthlyIncome: 32000,
    currency: 'ZAR',
    maritalStatus: 'SINGLE',
    householdSize: 4,
    housingType: 'LIVE_WITH_FAMILY',
    hasVehicle: false,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'SOCIAL',
    exerciseFrequency: 'ONCE_WEEK',
    techSavviness: 'INTERMEDIATE',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'Instagram', 'TikTok'],
    hobbies: ['Fashion', 'Dancing', 'Networking events'],
    interests: ['Entrepreneurship', 'Fashion', 'Self-improvement'],
    shoppingPreference: 'MIXED',
    priceConsciousness: 'HIGH',
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.89,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === FINANCE & ACCOUNTING ===
  {
    id: 'persona-008',
    tenantId: 'demo-tenant',
    firstName: 'Mohammed',
    lastName: 'Patel',
    avatarSeed: 'mohammed-patel-008',
    bio: 'Chartered accountant specializing in small business taxation. Third-generation family business advisor.',
    age: 52,
    ageRange: 'RANGE_45_54',
    gender: 'MALE',
    heightCm: 170,
    eyeColor: 'Brown',
    hairColor: 'Grey',
    ethnicity: 'Indian',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Johannesburg',
    urbanization: 'SUBURBAN',
    educationLevel: 'MASTERS',
    fieldOfStudy: 'Accounting',
    almaMater: 'University of the Witwatersrand',
    graduationYear: 1996,
    employmentStatus: 'SELF_EMPLOYED',
    profession: 'Accountant',
    jobTitle: 'Chartered Accountant',
    industry: 'Finance',
    company: 'Patel & Associates',
    yearsInRole: 20,
    yearsInIndustry: 28,
    incomeRange: 'RANGE_150K_200K',
    monthlyIncome: 170000,
    currency: 'ZAR',
    maritalStatus: 'MARRIED',
    householdSize: 5,
    numberOfChildren: 3,
    housingType: 'OWN_HOUSE',
    hasVehicle: true,
    vehicleCount: 3,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'NEVER',
    dietType: 'HALAL',
    techSavviness: 'INTERMEDIATE',
    primaryDevice: 'DESKTOP',
    socialPlatforms: ['WhatsApp', 'LinkedIn'],
    hobbies: ['Cricket', 'Reading', 'Community service'],
    values: ['Family', 'Faith', 'Community'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.90,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === YOUNG PROFESSIONAL ===
  {
    id: 'persona-009',
    tenantId: 'demo-tenant',
    firstName: 'Zanele',
    lastName: 'Khumalo',
    avatarSeed: 'zanele-khumalo-009',
    bio: 'Recent marketing graduate navigating the job market. Active on social media and interested in digital marketing.',
    age: 24,
    ageRange: 'RANGE_18_24',
    gender: 'FEMALE',
    heightCm: 164,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Johannesburg',
    township: 'Diepkloof',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'BACHELORS',
    fieldOfStudy: 'Marketing',
    almaMater: 'University of Johannesburg',
    graduationYear: 2024,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Marketing Coordinator',
    jobTitle: 'Junior Marketing Coordinator',
    industry: 'Marketing',
    yearsInRole: 1,
    yearsInIndustry: 1,
    incomeRange: 'UNDER_25K',
    monthlyIncome: 22000,
    currency: 'ZAR',
    maritalStatus: 'SINGLE',
    householdSize: 4,
    housingType: 'LIVE_WITH_FAMILY',
    hasVehicle: false,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'SOCIAL',
    exerciseFrequency: 'FEW_TIMES_WEEK',
    techSavviness: 'ADVANCED',
    primaryDevice: 'MOBILE',
    screenTimeHours: 6,
    socialPlatforms: ['Instagram', 'TikTok', 'Twitter', 'LinkedIn', 'WhatsApp'],
    hobbies: ['Content creation', 'Gym', 'Fashion'],
    interests: ['Digital marketing', 'Influencer culture', 'Travel'],
    shoppingPreference: 'ONLINE',
    priceConsciousness: 'HIGH',
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.87,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === SKILLED TRADES ===
  {
    id: 'persona-010',
    tenantId: 'demo-tenant',
    firstName: 'Pieter',
    lastName: 'Botha',
    avatarSeed: 'pieter-botha-010',
    bio: 'Experienced electrician running his own contracting business. Focused on renewable energy installations.',
    age: 41,
    ageRange: 'RANGE_35_44',
    gender: 'MALE',
    heightCm: 180,
    eyeColor: 'Green',
    hairColor: 'Brown',
    ethnicity: 'White',
    country: 'South Africa',
    region: 'Western Cape',
    city: 'Cape Town',
    urbanization: 'SUBURBAN',
    educationLevel: 'VOCATIONAL',
    fieldOfStudy: 'Electrical Engineering',
    employmentStatus: 'SELF_EMPLOYED',
    profession: 'Electrician',
    jobTitle: 'Master Electrician',
    industry: 'Construction',
    company: 'Botha Electrical',
    yearsInRole: 15,
    yearsInIndustry: 20,
    incomeRange: 'RANGE_75K_100K',
    monthlyIncome: 90000,
    currency: 'ZAR',
    maritalStatus: 'MARRIED',
    householdSize: 4,
    numberOfChildren: 2,
    housingType: 'OWN_HOUSE',
    hasVehicle: true,
    vehicleCount: 2,
    smokingStatus: 'REGULAR', // Tradesperson who smokes
    alcoholConsumption: 'MODERATE',
    exerciseFrequency: 'RARELY',
    techSavviness: 'INTERMEDIATE',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'Facebook'],
    hobbies: ['Rugby', 'Braai', 'Fishing'],
    interests: ['Solar power', 'Load shedding solutions', 'DIY'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.86,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === ENTREPRENEUR ===
  {
    id: 'persona-011',
    tenantId: 'demo-tenant',
    firstName: 'Themba',
    lastName: 'Zulu',
    avatarSeed: 'themba-zulu-011',
    bio: 'Serial entrepreneur with three businesses. Passionate about youth empowerment and township economics.',
    age: 35,
    ageRange: 'RANGE_35_44',
    gender: 'MALE',
    heightCm: 176,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Johannesburg',
    township: 'Tembisa',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'HIGH_SCHOOL',
    employmentStatus: 'SELF_EMPLOYED',
    profession: 'Entrepreneur',
    jobTitle: 'Founder & CEO',
    industry: 'Multiple',
    yearsInRole: 10,
    yearsInIndustry: 12,
    incomeRange: 'RANGE_100K_150K',
    monthlyIncome: 130000,
    currency: 'ZAR',
    maritalStatus: 'MARRIED',
    householdSize: 5,
    numberOfChildren: 3,
    housingType: 'OWN_HOUSE',
    hasVehicle: true,
    vehicleCount: 2,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'SOCIAL',
    exerciseFrequency: 'ONCE_WEEK',
    techSavviness: 'ADVANCED',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'LinkedIn', 'Twitter', 'Instagram'],
    hobbies: ['Networking', 'Motivational speaking', 'Soccer'],
    interests: ['Township economy', 'Youth empowerment', 'Fintech'],
    values: ['Hustle', 'Community', 'Legacy'],
    decisionMakingRole: 'DECISION_MAKER',
    budgetAuthority: 'UNLIMITED',
    companySize: 'SMB',
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.92,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === RETIRED ===
  {
    id: 'persona-012',
    tenantId: 'demo-tenant',
    firstName: 'Margaret',
    lastName: 'Smith',
    avatarSeed: 'margaret-smith-012',
    bio: 'Retired school principal now focused on grandchildren and community garden projects.',
    age: 68,
    ageRange: 'RANGE_65_PLUS',
    gender: 'FEMALE',
    heightCm: 158,
    eyeColor: 'Blue',
    hairColor: 'White',
    ethnicity: 'White',
    country: 'South Africa',
    region: 'Eastern Cape',
    city: 'Port Elizabeth',
    urbanization: 'SUBURBAN',
    educationLevel: 'MASTERS',
    fieldOfStudy: 'Education',
    employmentStatus: 'RETIRED',
    profession: 'Educator',
    jobTitle: 'Retired Principal',
    industry: 'Education',
    yearsInIndustry: 40,
    incomeRange: 'RANGE_50K_75K',
    monthlyIncome: 55000,
    currency: 'ZAR',
    maritalStatus: 'WIDOWED',
    householdSize: 1,
    numberOfChildren: 3,
    housingType: 'OWN_HOUSE',
    hasVehicle: true,
    vehicleCount: 1,
    hasPets: true,
    petTypes: ['Cat'],
    smokingStatus: 'NEVER',
    alcoholConsumption: 'RARELY',
    exerciseFrequency: 'ONCE_WEEK',
    hasChronicConditions: true,
    chronicConditions: ['Arthritis', 'Hypertension'],
    techSavviness: 'BASIC',
    primaryDevice: 'TABLET',
    socialPlatforms: ['WhatsApp', 'Facebook'],
    hobbies: ['Gardening', 'Reading', 'Church activities', 'Grandchildren'],
    interests: ['Community service', 'Health', 'Family'],
    values: ['Family', 'Faith', 'Education'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.88,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === STUDENT ===
  {
    id: 'persona-013',
    tenantId: 'demo-tenant',
    firstName: 'Bongani',
    lastName: 'Ndlovu',
    avatarSeed: 'bongani-ndlovu-013',
    bio: 'Engineering student working part-time to fund studies. First in family to attend university.',
    age: 22,
    ageRange: 'RANGE_18_24',
    gender: 'MALE',
    heightCm: 172,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Gauteng',
    city: 'Johannesburg',
    township: 'Orange Farm',
    urbanization: 'SUBURBAN',
    educationLevel: 'SOME_COLLEGE',
    fieldOfStudy: 'Mechanical Engineering',
    almaMater: 'University of Johannesburg',
    employmentStatus: 'STUDENT',
    profession: 'Student',
    jobTitle: 'Part-time Tutor',
    industry: 'Education',
    incomeRange: 'UNDER_25K',
    monthlyIncome: 5000,
    currency: 'ZAR',
    maritalStatus: 'SINGLE',
    householdSize: 6,
    housingType: 'LIVE_WITH_FAMILY',
    hasVehicle: false,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'RARELY',
    exerciseFrequency: 'FEW_TIMES_WEEK',
    techSavviness: 'ADVANCED',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'Twitter', 'YouTube'],
    hobbies: ['Soccer', 'Gaming', 'Tutoring'],
    interests: ['Renewable energy', 'Career development', 'Technology'],
    values: ['Education', 'Family', 'Hard work'],
    priceConsciousness: 'HIGH',
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.85,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === HOSPITALITY ===
  {
    id: 'persona-014',
    tenantId: 'demo-tenant',
    firstName: 'Sarah',
    lastName: 'Williams',
    avatarSeed: 'sarah-williams-014',
    bio: "Hotel manager in Cape Town's hospitality industry. Passionate about sustainable tourism.",
    age: 36,
    ageRange: 'RANGE_35_44',
    gender: 'FEMALE',
    heightCm: 170,
    eyeColor: 'Hazel',
    hairColor: 'Blonde',
    ethnicity: 'Coloured',
    country: 'South Africa',
    region: 'Western Cape',
    city: 'Cape Town',
    urbanization: 'URBAN_MAJOR_CITY',
    educationLevel: 'BACHELORS',
    fieldOfStudy: 'Hospitality Management',
    almaMater: 'Cape Peninsula University of Technology',
    graduationYear: 2011,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Hotel Manager',
    jobTitle: 'Operations Manager',
    industry: 'Hospitality',
    yearsInRole: 5,
    yearsInIndustry: 13,
    incomeRange: 'RANGE_75K_100K',
    monthlyIncome: 78000,
    currency: 'ZAR',
    maritalStatus: 'DOMESTIC_PARTNERSHIP',
    householdSize: 2,
    housingType: 'RENT_APARTMENT',
    hasVehicle: true,
    smokingStatus: 'FORMER',
    alcoholConsumption: 'SOCIAL',
    exerciseFrequency: 'FEW_TIMES_WEEK',
    dietType: 'PESCATARIAN',
    techSavviness: 'ADVANCED',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['Instagram', 'LinkedIn', 'WhatsApp'],
    hobbies: ['Hiking', 'Wine tasting', 'Travel'],
    interests: ['Sustainable tourism', 'Local food', 'Wellness'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.91,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },

  // === GOVERNMENT/PUBLIC SECTOR ===
  {
    id: 'persona-015',
    tenantId: 'demo-tenant',
    firstName: 'Lindiwe',
    lastName: 'Mahlangu',
    avatarSeed: 'lindiwe-mahlangu-015',
    bio: 'Government social worker dedicated to child welfare. Works in challenging conditions with limited resources.',
    age: 40,
    ageRange: 'RANGE_35_44',
    gender: 'FEMALE',
    heightCm: 165,
    eyeColor: 'Brown',
    hairColor: 'Black',
    ethnicity: 'Black African',
    country: 'South Africa',
    region: 'Mpumalanga',
    city: 'Nelspruit',
    urbanization: 'URBAN_SMALL_CITY',
    educationLevel: 'BACHELORS',
    fieldOfStudy: 'Social Work',
    almaMater: 'University of Pretoria',
    graduationYear: 2007,
    employmentStatus: 'EMPLOYED_FULL_TIME',
    profession: 'Social Worker',
    jobTitle: 'Senior Social Worker',
    industry: 'Government',
    yearsInRole: 10,
    yearsInIndustry: 16,
    incomeRange: 'RANGE_50K_75K',
    monthlyIncome: 62000,
    currency: 'ZAR',
    maritalStatus: 'MARRIED',
    householdSize: 4,
    numberOfChildren: 2,
    housingType: 'OWN_HOUSE',
    hasVehicle: true,
    smokingStatus: 'NEVER',
    alcoholConsumption: 'RARELY',
    exerciseFrequency: 'RARELY',
    stressLevel: 'HIGH',
    techSavviness: 'BASIC',
    primaryDevice: 'MOBILE',
    socialPlatforms: ['WhatsApp', 'Facebook'],
    hobbies: ['Church activities', 'Reading', 'Cooking'],
    interests: ['Child welfare', 'Community development', 'Mental health'],
    values: ['Service', 'Faith', 'Family'],
    generatedAt: '2026-02-09T10:00:00Z',
    qualityScore: 0.89,
    createdAt: '2026-02-09T10:00:00Z',
    updatedAt: '2026-02-09T10:00:00Z',
  },
];

/**
 * Get unique values for filter options
 */
export function getFilterOptions() {
  const professions = [...new Set(samplePersonas.map((p) => p.profession).filter(Boolean))];
  const industries = [...new Set(samplePersonas.map((p) => p.industry).filter(Boolean))];
  const cities = [...new Set(samplePersonas.map((p) => p.city).filter(Boolean))];
  const townships = [...new Set(samplePersonas.map((p) => p.township).filter(Boolean))];

  return {
    professions: professions.map((p) => ({ value: p!, label: p! })),
    industries: industries.map((i) => ({ value: i!, label: i! })),
    cities: cities.map((c) => ({ value: c!, label: c! })),
    townships: townships.map((t) => ({ value: t!, label: t! })),
  };
}

export default samplePersonas;
