import type { Cohort } from "../_lib/types";

export const cohorts: Cohort[] = [
  {
    id: "coh_1",
    name: "Power Users",
    type: "dynamic",
    size: 1842,
    created: "Nov 10, 2025",
    lastCalculated: "2h ago",
    filters: "Events > 100 in last 30 days AND Sessions > 10",
    sizeOverTime: [
      { date: "Jan 6", size: 1620 },
      { date: "Jan 13", size: 1650 },
      { date: "Jan 20", size: 1710 },
      { date: "Jan 27", size: 1690 },
      { date: "Feb 3", size: 1750 },
      { date: "Feb 10", size: 1800 },
      { date: "Feb 17", size: 1842 },
    ],
  },
  {
    id: "coh_2",
    name: "Churned Users",
    type: "dynamic",
    size: 3210,
    created: "Dec 1, 2025",
    lastCalculated: "2h ago",
    filters: "Last seen > 30 days ago AND Events > 5 lifetime",
    sizeOverTime: [
      { date: "Jan 6", size: 2900 },
      { date: "Jan 13", size: 2980 },
      { date: "Jan 20", size: 3050 },
      { date: "Jan 27", size: 3100 },
      { date: "Feb 3", size: 3140 },
      { date: "Feb 10", size: 3180 },
      { date: "Feb 17", size: 3210 },
    ],
  },
  {
    id: "coh_3",
    name: "Enterprise Accounts",
    type: "static",
    size: 248,
    created: "Oct 15, 2025",
    lastCalculated: "—",
    filters: "Plan = Enterprise",
    sizeOverTime: [
      { date: "Jan 6", size: 220 },
      { date: "Jan 13", size: 225 },
      { date: "Jan 20", size: 230 },
      { date: "Jan 27", size: 235 },
      { date: "Feb 3", size: 240 },
      { date: "Feb 10", size: 245 },
      { date: "Feb 17", size: 248 },
    ],
  },
  {
    id: "coh_4",
    name: "Beta Testers",
    type: "static",
    size: 512,
    created: "Jan 5, 2026",
    lastCalculated: "—",
    filters: "Feature flag 'beta-access' = true",
    sizeOverTime: [
      { date: "Jan 6", size: 480 },
      { date: "Jan 13", size: 490 },
      { date: "Jan 20", size: 495 },
      { date: "Jan 27", size: 500 },
      { date: "Feb 3", size: 505 },
      { date: "Feb 10", size: 510 },
      { date: "Feb 17", size: 512 },
    ],
  },
  {
    id: "coh_5",
    name: "Mobile Users",
    type: "dynamic",
    size: 4620,
    created: "Nov 22, 2025",
    lastCalculated: "2h ago",
    filters: "Device type = Mobile OR Tablet",
    sizeOverTime: [
      { date: "Jan 6", size: 4100 },
      { date: "Jan 13", size: 4200 },
      { date: "Jan 20", size: 4300 },
      { date: "Jan 27", size: 4350 },
      { date: "Feb 3", size: 4450 },
      { date: "Feb 10", size: 4540 },
      { date: "Feb 17", size: 4620 },
    ],
  },
  {
    id: "coh_6",
    name: "Trial Converts",
    type: "dynamic",
    size: 890,
    created: "Jan 15, 2026",
    lastCalculated: "2h ago",
    filters: "Plan changed from Free to Pro/Enterprise in last 90 days",
    sizeOverTime: [
      { date: "Jan 6", size: 720 },
      { date: "Jan 13", size: 750 },
      { date: "Jan 20", size: 780 },
      { date: "Jan 27", size: 810 },
      { date: "Feb 3", size: 840 },
      { date: "Feb 10", size: 865 },
      { date: "Feb 17", size: 890 },
    ],
  },
];
