import type { FeatureFlag } from "../_lib/types";

export const featureFlags: FeatureFlag[] = [
  {
    id: "ff_1",
    key: "new-dashboard-v2",
    name: "New Dashboard V2",
    description: "Redesigned dashboard with real-time metrics and AI insights panel.",
    type: "boolean",
    status: "active",
    rolloutPercentage: 75,
    filters: [
      { property: "plan", operator: "is", value: "Pro, Enterprise" },
    ],
    createdAt: "Jan 15, 2026",
  },
  {
    id: "ff_2",
    key: "checkout-flow-ab",
    name: "Checkout Flow A/B",
    description: "Multi-step checkout vs single-page checkout test.",
    type: "multivariate",
    status: "active",
    rolloutPercentage: 100,
    variants: [
      { key: "control", name: "Multi-step (Control)", rollout: 50 },
      { key: "single-page", name: "Single Page", rollout: 50 },
    ],
    createdAt: "Feb 1, 2026",
  },
  {
    id: "ff_3",
    key: "ai-search",
    name: "AI-Powered Search",
    description: "Natural language search across docs, settings, and analytics.",
    type: "boolean",
    status: "active",
    rolloutPercentage: 30,
    filters: [
      { property: "country", operator: "is", value: "US, UK, CA" },
    ],
    createdAt: "Feb 5, 2026",
  },
  {
    id: "ff_4",
    key: "dark-mode-beta",
    name: "Dark Mode Beta",
    description: "Full dark theme across all pages and components.",
    type: "boolean",
    status: "active",
    rolloutPercentage: 100,
    createdAt: "Dec 10, 2025",
  },
  {
    id: "ff_5",
    key: "notification-center",
    name: "Notification Center",
    description: "In-app notification bell with real-time alerts and digest.",
    type: "boolean",
    status: "paused",
    rolloutPercentage: 0,
    createdAt: "Jan 28, 2026",
  },
  {
    id: "ff_6",
    key: "pricing-page-redesign",
    name: "Pricing Page Redesign",
    description: "New pricing page with comparison table and FAQ section.",
    type: "multivariate",
    status: "draft",
    rolloutPercentage: 0,
    variants: [
      { key: "control", name: "Current Design", rollout: 34 },
      { key: "minimal", name: "Minimal Cards", rollout: 33 },
      { key: "comparison", name: "Comparison Table", rollout: 33 },
    ],
    createdAt: "Feb 12, 2026",
  },
  {
    id: "ff_7",
    key: "export-csv",
    name: "CSV Export",
    description: "Allow users to export analytics data as CSV files.",
    type: "boolean",
    status: "active",
    rolloutPercentage: 100,
    createdAt: "Nov 20, 2025",
  },
  {
    id: "ff_8",
    key: "onboarding-v3",
    name: "Onboarding V3",
    description: "Guided onboarding with interactive product tour and checklist.",
    type: "boolean",
    status: "paused",
    rolloutPercentage: 15,
    filters: [
      { property: "signup_date", operator: "after", value: "2026-02-01" },
    ],
    createdAt: "Feb 8, 2026",
  },
];
