import type { SessionReplay } from "../_lib/types";

export const sessions: SessionReplay[] = [
  {
    id: "sess_1",
    user: "Alex Chen",
    email: "alex.chen@example.com",
    duration: "4m 32s",
    pagesViewed: 7,
    events: 24,
    startTime: "2 hours ago",
    country: "United States",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/homepage" },
      { time: "0:12", event: "Page View", detail: "/pricing" },
      { time: "0:45", event: "Button Click", detail: "Compare Plans" },
      { time: "1:20", event: "Page View", detail: "/signup" },
      { time: "1:55", event: "Form Submit", detail: "Email entered" },
      { time: "2:30", event: "Page View", detail: "/onboarding" },
      { time: "3:15", event: "Button Click", detail: "Skip Tour" },
      { time: "3:40", event: "Page View", detail: "/dashboard" },
      { time: "4:10", event: "Button Click", detail: "Create Chart" },
      { time: "4:32", event: "Session End" },
    ],
  },
  {
    id: "sess_2",
    user: "Jordan Patel",
    email: "jordan.patel@example.com",
    duration: "8m 15s",
    pagesViewed: 12,
    events: 41,
    startTime: "3 hours ago",
    country: "United Kingdom",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/dashboard" },
      { time: "0:30", event: "Button Click", detail: "Date Range: Last 30d" },
      { time: "1:15", event: "Page View", detail: "/trends" },
      { time: "2:00", event: "Button Click", detail: "Add Event: Purchase" },
      { time: "3:20", event: "Page View", detail: "/funnels" },
      { time: "4:45", event: "Button Click", detail: "Export CSV" },
      { time: "5:30", event: "Page View", detail: "/retention" },
      { time: "6:50", event: "Page View", detail: "/people" },
      { time: "7:30", event: "Button Click", detail: "Search Users" },
      { time: "8:15", event: "Session End" },
    ],
  },
  {
    id: "sess_3",
    user: "Taylor Kim",
    email: "taylor.kim@example.com",
    duration: "2m 05s",
    pagesViewed: 3,
    events: 8,
    startTime: "5 hours ago",
    country: "Canada",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/homepage" },
      { time: "0:20", event: "Page View", detail: "/features" },
      { time: "0:55", event: "Scroll", detail: "75% page depth" },
      { time: "1:30", event: "Page View", detail: "/blog/analytics-guide" },
      { time: "2:05", event: "Session End" },
    ],
  },
  {
    id: "sess_4",
    user: "Morgan Rodriguez",
    email: "morgan.r@example.com",
    duration: "12m 48s",
    pagesViewed: 15,
    events: 56,
    startTime: "6 hours ago",
    country: "Germany",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/dashboard" },
      { time: "0:45", event: "Page View", detail: "/experiments" },
      { time: "2:10", event: "Button Click", detail: "Create Experiment" },
      { time: "3:30", event: "Form Submit", detail: "Experiment saved" },
      { time: "4:15", event: "Page View", detail: "/feature-flags" },
      { time: "5:40", event: "Button Click", detail: "Toggle flag: ai-search" },
      { time: "6:20", event: "Page View", detail: "/sql" },
      { time: "8:00", event: "Button Click", detail: "Run Query" },
      { time: "9:30", event: "Page View", detail: "/people" },
      { time: "11:00", event: "Page View", detail: "/people/usr_42" },
      { time: "12:48", event: "Session End" },
    ],
  },
  {
    id: "sess_5",
    user: "Casey Okafor",
    email: "casey.o@example.com",
    duration: "6m 10s",
    pagesViewed: 8,
    events: 29,
    startTime: "8 hours ago",
    country: "Australia",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/dashboard" },
      { time: "0:25", event: "Page View", detail: "/trends" },
      { time: "1:40", event: "Button Click", detail: "Chart Type: Area" },
      { time: "2:15", event: "Button Click", detail: "Add Breakdown: Country" },
      { time: "3:00", event: "Page View", detail: "/retention" },
      { time: "4:20", event: "Page View", detail: "/lifecycle" },
      { time: "5:30", event: "Page View", detail: "/cohorts" },
      { time: "6:10", event: "Session End" },
    ],
  },
  {
    id: "sess_6",
    user: "Riley Anderson",
    email: "riley.a@example.com",
    duration: "1m 15s",
    pagesViewed: 2,
    events: 5,
    startTime: "10 hours ago",
    country: "France",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/homepage" },
      { time: "0:30", event: "Page View", detail: "/pricing" },
      { time: "0:50", event: "Scroll", detail: "50% page depth" },
      { time: "1:15", event: "Session End" },
    ],
  },
  {
    id: "sess_7",
    user: "Quinn Müller",
    email: "quinn.m@example.com",
    duration: "9m 40s",
    pagesViewed: 11,
    events: 38,
    startTime: "12 hours ago",
    country: "Japan",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/dashboard" },
      { time: "0:35", event: "Page View", detail: "/surveys" },
      { time: "1:50", event: "Button Click", detail: "View NPS Results" },
      { time: "3:00", event: "Page View", detail: "/session-replay" },
      { time: "4:20", event: "Button Click", detail: "Watch Session #3" },
      { time: "6:00", event: "Page View", detail: "/paths" },
      { time: "7:30", event: "Button Click", detail: "Change Start: Pricing" },
      { time: "8:45", event: "Page View", detail: "/dashboard" },
      { time: "9:40", event: "Session End" },
    ],
  },
  {
    id: "sess_8",
    user: "Avery Williams",
    email: "avery.w@example.com",
    duration: "3m 20s",
    pagesViewed: 5,
    events: 14,
    startTime: "1 day ago",
    country: "Brazil",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/homepage" },
      { time: "0:15", event: "Page View", detail: "/features" },
      { time: "0:50", event: "Page View", detail: "/pricing" },
      { time: "1:30", event: "Button Click", detail: "Start Free Trial" },
      { time: "2:00", event: "Page View", detail: "/signup" },
      { time: "2:45", event: "Form Submit", detail: "Registration complete" },
      { time: "3:20", event: "Session End" },
    ],
  },
];
