import type { SessionReplay } from "../_lib/types";

export const sessions: SessionReplay[] = [
  {
    id: "sess_1",
    user: "Dr. Sipho Nkosi",
    email: "sipho.nkosi@medpractice.co.za",
    duration: "4m 45s",
    pagesViewed: 6,
    events: 18,
    startTime: "2 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:15", event: "Page View", detail: "/browse-paths" },
      { time: "0:42", event: "Scroll", detail: "Browsed Medical Leadership path" },
      { time: "1:10", event: "Page View", detail: "/path/medical-leadership" },
      { time: "1:45", event: "Button Click", detail: "View Path Details" },
      { time: "2:20", event: "Page View", detail: "/path/medical-leadership/milestone-2" },
      { time: "3:00", event: "Button Click", detail: "Start Go-Card" },
      { time: "3:35", event: "Page View", detail: "/go-card/reflective-practice" },
      { time: "4:20", event: "gocard_completed", detail: "Reflective Practice Go-Card" },
      { time: "4:45", event: "Session End" },
    ],
  },
  {
    id: "sess_2",
    user: "Adv. Naledi Mokoena",
    email: "naledi.mokoena@lawchambers.co.za",
    duration: "7m 30s",
    pagesViewed: 9,
    events: 32,
    startTime: "3 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:20", event: "Page View", detail: "/my-progress" },
      { time: "0:55", event: "Button Click", detail: "Continue Path: Legal Practice Management" },
      { time: "1:30", event: "Page View", detail: "/go-card/client-intake-process" },
      { time: "2:15", event: "gocard_completed", detail: "Client Intake Process" },
      { time: "2:40", event: "Page View", detail: "/go-card/brief-preparation" },
      { time: "3:50", event: "gocard_completed", detail: "Brief Preparation" },
      { time: "4:10", event: "Page View", detail: "/go-card/court-etiquette" },
      { time: "5:30", event: "gocard_completed", detail: "Court Etiquette" },
      { time: "5:50", event: "milestone_completed", detail: "Milestone: Professional Foundations" },
      { time: "6:20", event: "Page View", detail: "/evidence-portfolio" },
      { time: "7:30", event: "Session End" },
    ],
  },
  {
    id: "sess_3",
    user: "Thandi van der Merwe CA(SA)",
    email: "thandi.vdm@accounting.co.za",
    duration: "5m 20s",
    pagesViewed: 5,
    events: 22,
    startTime: "4 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:18", event: "Page View", detail: "/ai-tools" },
      { time: "0:40", event: "Button Click", detail: "Open CV Builder" },
      { time: "0:55", event: "Page View", detail: "/ai-tools/cv-builder" },
      { time: "1:20", event: "Button Click", detail: "Select Template: Professional" },
      { time: "1:50", event: "ai_tool_used", detail: "Generated CV Summary" },
      { time: "2:30", event: "Button Click", detail: "Add Evidence to CV" },
      { time: "3:15", event: "ai_tool_used", detail: "AI Skills Extraction" },
      { time: "4:00", event: "Button Click", detail: "Download CV as PDF" },
      { time: "4:25", event: "cv_builder_used", detail: "CV exported successfully" },
      { time: "5:20", event: "Session End" },
    ],
  },
  {
    id: "sess_4",
    user: "Eng. Johan Pretorius",
    email: "johan.pretorius@engineering.co.za",
    duration: "3m 40s",
    pagesViewed: 5,
    events: 15,
    startTime: "5 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:12", event: "Page View", detail: "/evidence-portfolio" },
      { time: "0:35", event: "Scroll", detail: "Reviewed 12 evidence items" },
      { time: "1:00", event: "Button Click", detail: "View Evidence: Project Report" },
      { time: "1:30", event: "Page View", detail: "/evidence/eng-project-report-042" },
      { time: "2:00", event: "Button Click", detail: "Edit Tags" },
      { time: "2:25", event: "evidence_uploaded", detail: "Added CPD certificate" },
      { time: "3:00", event: "Button Click", detail: "Share Portfolio Link" },
      { time: "3:40", event: "Session End" },
    ],
  },
  {
    id: "sess_5",
    user: "Adv. Lerato Dlamini",
    email: "lerato.dlamini@legal.co.za",
    duration: "4m 15s",
    pagesViewed: 6,
    events: 20,
    startTime: "6 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:10", event: "Page View", detail: "/browse-paths" },
      { time: "0:30", event: "Button Click", detail: "Filter: Career Transition" },
      { time: "0:55", event: "Page View", detail: "/path/land-your-next-job" },
      { time: "1:20", event: "Scroll", detail: "Read path overview and milestones" },
      { time: "1:50", event: "Button Click", detail: "Start This Path" },
      { time: "2:10", event: "path_started", detail: "Land Your Next Job" },
      { time: "2:35", event: "Page View", detail: "/path/land-your-next-job/milestone-1" },
      { time: "3:10", event: "Button Click", detail: "Begin First Go-Card" },
      { time: "3:40", event: "Page View", detail: "/go-card/career-audit" },
      { time: "4:15", event: "Session End" },
    ],
  },
  {
    id: "sess_6",
    user: "Zanele Mthembu CA(SA)",
    email: "zanele.mthembu@audit.co.za",
    duration: "6m 05s",
    pagesViewed: 7,
    events: 28,
    startTime: "8 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:15", event: "Page View", detail: "/my-progress" },
      { time: "0:40", event: "Button Click", detail: "View Milestone: Tax Specialisation" },
      { time: "1:05", event: "Page View", detail: "/path/accounting-excellence/milestone-3" },
      { time: "1:35", event: "Scroll", detail: "Reviewed milestone requirements" },
      { time: "2:00", event: "Button Click", detail: "Submit Final Go-Card" },
      { time: "2:45", event: "gocard_completed", detail: "Tax Compliance Review" },
      { time: "3:10", event: "evidence_uploaded", detail: "Tax advisory report" },
      { time: "3:45", event: "milestone_completed", detail: "Milestone: Tax Specialisation" },
      { time: "4:20", event: "Button Click", detail: "Share Achievement" },
      { time: "4:50", event: "Page View", detail: "/evidence-portfolio" },
      { time: "6:05", event: "Session End" },
    ],
  },
  {
    id: "sess_7",
    user: "Dr. Nomsa Khumalo",
    email: "nomsa.khumalo@clinic.co.za",
    duration: "5m 50s",
    pagesViewed: 4,
    events: 24,
    startTime: "10 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:08", event: "Button Click", detail: "Open MI Chat" },
      { time: "0:20", event: "Page View", detail: "/mi-chat" },
      { time: "0:40", event: "mi_chat_opened", detail: "Career advice session started" },
      { time: "1:10", event: "Button Click", detail: "Asked: Best path for specialisation?" },
      { time: "1:45", event: "ai_tool_used", detail: "MI recommended 3 paths" },
      { time: "2:20", event: "Button Click", detail: "Asked: How to build CPD portfolio?" },
      { time: "3:00", event: "ai_tool_used", detail: "MI generated portfolio plan" },
      { time: "3:40", event: "Button Click", detail: "Asked: Timeline for career transition?" },
      { time: "4:15", event: "ai_tool_used", detail: "MI created 6-month roadmap" },
      { time: "5:00", event: "Button Click", detail: "Save Chat to MyDNA" },
      { time: "5:50", event: "Session End" },
    ],
  },
  {
    id: "sess_8",
    user: "Eng. Palesa Molefe",
    email: "palesa.molefe@civileng.co.za",
    duration: "3m 55s",
    pagesViewed: 5,
    events: 16,
    startTime: "12 hours ago",
    country: "South Africa",
    eventTimeline: [
      { time: "0:00", event: "Session Start", detail: "/home" },
      { time: "0:10", event: "Page View", detail: "/mydna" },
      { time: "0:30", event: "Scroll", detail: "Reviewed professional profile summary" },
      { time: "0:55", event: "Button Click", detail: "View Skills Map" },
      { time: "1:20", event: "Page View", detail: "/mydna/skills" },
      { time: "1:50", event: "Button Click", detail: "Update: Added Project Management" },
      { time: "2:15", event: "mydna_updated", detail: "Skills profile updated" },
      { time: "2:40", event: "Page View", detail: "/mydna/career-insights" },
      { time: "3:10", event: "Button Click", detail: "View Recommended Paths" },
      { time: "3:30", event: "Page View", detail: "/browse-paths?recommended=true" },
      { time: "3:55", event: "Session End" },
    ],
  },
];
